Controller exercises
VishwasMalhotra/depot pull request #3
Opened 2018-06-25 13:35 UTC by VishwasMalhotra

2018-06-26 11:07 UTC, sawangupta92 requested changes

2018-06-26 11:07 UTC, sawangupta92 commented on app/assets/javascripts/admin/base.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
temp commit is not a good commit name

2018-06-26 11:07 UTC, sawangupta92 commented on app/assets/javascripts/admin/categories.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
I think you have scaffold here, but it is really better if you don't use it in training.

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/admin/base_controller.rb
> +    unless current_user.role.eql?('admin')
indentation issue

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/admin/base_controller.rb
> +    unless current_user.role.eql?('admin')
let's add this method on user instead, and here it will be called like this.

``` current_user.admin? ```

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/admin/categories_controller.rb
> +    @category_products = Category.find_by_id(params[:id])
this is category not category_products

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/admin/categories_controller.rb
> +    @category_products = Category.find_by_id(params[:id])
what if Category is not found

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/admin/reports_controller.rb
> +  def filter_by_date
do we really need this as a before_action? I guess it be better if we directly call this method from the action itself

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/admin/reports_controller.rb
> +    if (params[:start_date] && params[:end_date]) && !(params[:start_date].empty? || params[:end_date].empty?)
what if params[:start_date] is not present but params[:end_date] is present?

try to simplify this condition

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/application_controller.rb
> +    start_time = Time.now
use Time.current

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/application_controller.rb
>      def authorize
this seems authentication and not authorization

2018-06-26 11:07 UTC, sawangupta92 commented on app/controllers/sessions_controller.rb
> +      redirect_to admin_reports_path and return if user.role.eql?('admin')
same as above

2018-06-26 11:07 UTC, sawangupta92 commented on app/views/admin/categories/books.html.erb
> +    <ul>
this ul has never been closed

2018-06-26 11:07 UTC, sawangupta92 commented on app/views/admin/reports/index.html.erb
> +
why extra lines?

2018-06-26 11:07 UTC, sawangupta92 commented on app/views/admin/reports/index.html.erb
> +    <% @orders.each do |order| %>
what if no records are found

2018-06-26 11:07 UTC, sawangupta92 commented on app/views/users/items.html.erb
> +        <td><%= item.product.title %></td>
indentations

2018-06-26 11:07 UTC, sawangupta92 commented on db/migrate/20180619065235_add_role_to_users.rb
> +    add_column :users, :role, :string, default: :user
why is this not an enum?

2018-07-03 06:33 UTC, vinay-mittal requested changes

2018-07-03 06:33 UTC, vinay-mittal commented on db/migrate/20180627112417_change_role_in_users.rb
> +  def change
make it irreversible migration.

2018-07-03 11:03 UTC, merged